### ISSUE TITLE
Empty Merge Request Table

### ISSUE THREAD

**Issue by NTXPabu** [btey/openproject-gitlab-integration#17]
Hi,

the Gitlab Merge Requests do not show up in the Merge Request Table in OpenProject.
We created a Merge Request like this in Gitlab:
**Picture**:
![gitlab](https://user-images.githubusercontent.com/111059521/184129715-ea46274a-d939-408a-a8f5-cbd4affb0d57.png)

**Request**:
```
{
  "object_kind": "merge_request",
  "event_type": "merge_request",
  "user": {
    "id": 16,
    "name": "te",
    "username": "te",
    "avatar_url": "https://secure.gravatar.com/avatar/69d1b0fb4e79c8d81ab73f4fe4f19c5b?s=80&d=identicon",
    "email": "[REDACTED]"
  },
  "project": {
    "id": 5,
    "name": "MServer",
    "description": "",
    "web_url": "xxx",
    "avatar_url": null,
    "git_ssh_url": "xxx",
    "git_http_url": "xxx",
    "namespace": "zzz",
    "visibility_level": 0,
    "path_with_namespace": "zzz/MServer",
    "default_branch": "main",
    "ci_config_path": null,
    "homepage": "xxx",
    "url": "xxx",
    "ssh_url": "xxx",
    "http_url": "xxx"
  },
  "object_attributes": {
    "assignee_id": null,
    "author_id": 16,
    "created_at": "2022-08-11 11:57:23 UTC",
    "description": "",
    "head_pipeline_id": null,
    "id": 10,
    "iid": 10,
    "last_edited_at": null,
    "last_edited_by_id": null,
    "merge_commit_sha": null,
    "merge_error": null,
    "merge_params": {
      "force_remove_source_branch": "1"
    },
    "merge_status": "preparing",
    "merge_user_id": null,
    "merge_when_pipeline_succeeds": false,
    "milestone_id": null,
    "source_branch": "feature/213-umgebung-aufsetzen",
    "source_project_id": 5,
    "state_id": 1,
    "target_branch": "main",
    "target_project_id": 5,
    "time_estimate": 0,
    "title": "Umgebung aufsetzen - OP#213",
    "updated_at": "2022-08-11 11:57:23 UTC",
    "updated_by_id": null,
    "url": "xxx",
    "source": {
      "id": 5,
      "name": "MServer",
      "description": "",
      "web_url": "xxx",
      "avatar_url": null,
      "git_ssh_url": "xxx",
      "git_http_url": "xxx",
      "namespace": "zzz",
      "visibility_level": 0,
      "path_with_namespace": "zzz/MServer",
      "default_branch": "main",
      "ci_config_path": null,
      "homepage": "xxx",
      "url": "xxx",
      "ssh_url": "xxx",
      "http_url": "xxxx"
    },
    "target": {
      "id": 5,
      "name": "MServer",
      "description": "",
      "web_url": "xxx",
      "avatar_url": null,
      "git_ssh_url": "xxx",
      "git_http_url": "xxx",
      "namespace": "zzz",
      "visibility_level": 0,
      "path_with_namespace": "zzz/MServer",
      "default_branch": "main",
      "ci_config_path": null,
      "homepage": "xxx",
      "url": "xxx",
      "ssh_url": "xxx",
      "http_url": "xxxt"
    },
    "last_commit": {
      "id": "c9f99340c7eb14e2fc29abba4feedbb0c50bfb3a",
      "message": "[#213] Umgebung aufsetzen\n\nxxx\n",
      "title": "[#213] Umgebung aufsetzen",
      "timestamp": "2022-08-10T11:36:13+02:00",
      "url": "https://xxx/-/commit/c9f99340c7eb14e2fc29abba4feedbb0c50bfb3a",
      "author": {
        "name": "yyy yyy",
        "email": "y@y.de"
      }
    },
    "work_in_progress": false,
    "total_time_spent": 0,
    "time_change": 0,
    "human_total_time_spent": null,
    "human_time_change": null,
    "human_time_estimate": null,
    "assignee_ids": [

    ],
    "state": "opened",
    "blocking_discussions_resolved": true,
    "action": "open"
  },
  "labels": [

  ],
  "changes": {
    "merge_status": {
      "previous": "unchecked",
      "current": "preparing"
    }
  },
  "repository": {
    "name": "MServer",
    "url": "xxx",
    "description": "",
    "homepage": "xxx"
  }
}
```

But we cant see the Merge Request in OpenProject:
![openproject](https://user-images.githubusercontent.com/111059521/184129953-fabfdbcd-7f18-483a-a58a-05e2aa372be8.png)

We use Gitlab Community Edition 14.9.2  and OpenProject 12.1.6.

**Comment by NTXPabu** [comment]
Debug Log from OpenProject:
```
D, [2022-08-11T10:58:34.692232 #69] DEBUG -- : (0.5ms) SELECT MAX("settings"."updated_at") FROM "settings"

D, [2022-08-11T10:58:34.695555 #69] DEBUG -- : Token::API Load (0.9ms) SELECT "tokens".* FROM "tokens" WHERE "tokens"."type" = $1 AND "tokens"."value" = $2 LIMIT $3 [["type", "Token::API"], ["value", "xxx"], ["LIMIT", 1]]

D, [2022-08-11T10:58:34.699005 #69] DEBUG -- : User Load (2.0ms) SELECT "users".* FROM "users" WHERE "users"."type" IN ($1, $2, $3, $4) AND "users"."id" = $5 LIMIT $6 [["type", "User"], ["type", "SystemUser"], ["type", "AnonymousUser"], ["type", "DeletedUser"], ["id", 11], ["LIMIT", 1]]

D, [2022-08-11T10:58:34.701943 #69] DEBUG -- : Token::API Load (0.3ms) SELECT "tokens".* FROM "tokens" WHERE "tokens"."type" = $1 AND "tokens"."value" = $2 LIMIT $3 [["type", "Token::API"], ["value", "xxx"], ["LIMIT", 1]]

D, [2022-08-11T10:58:34.703095 #69] DEBUG -- : User Load (0.2ms) SELECT "users".* FROM "users" WHERE "users"."type" IN ($1, $2, $3, $4) AND "users"."id" = $5 LIMIT $6 [["type", "User"], ["type", "SystemUser"], ["type", "AnonymousUser"], ["type", "DeletedUser"], ["id", 11], ["LIMIT", 1]]

D, [2022-08-11T10:58:34.703543 #69] DEBUG -- : Received gitlab webhook merge_request_hook

D, [2022-08-11T10:58:34.704490 #69] DEBUG -- : CACHE User Load (0.0ms) SELECT "users".* FROM "users" WHERE "users"."type" IN ($1, $2, $3, $4) AND "users"."id" = $5 LIMIT $6 [["type", "User"], ["type", "SystemUser"], ["type", "AnonymousUser"], ["type", "DeletedUser"], ["id", 11], ["LIMIT", 1]]

D, [2022-08-11T10:58:34.705606 #69] DEBUG -- : WorkPackage Load (0.3ms) SELECT "work_packages".* FROM "work_packages" WHERE "work_packages"."id" = $1 [["id", 213]]

D, [2022-08-11T10:58:34.706847 #69] DEBUG -- : Project Load (0.3ms) SELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 [["id", 5]]

D, [2022-08-11T10:58:34.707980 #69] DEBUG -- : (0.2ms) SELECT "enabled_modules"."name" FROM "enabled_modules" WHERE "enabled_modules"."project_id" = $1 [["project_id", 5]]

D, [2022-08-11T10:58:34.710701 #69] DEBUG -- : SQL (1.0ms) SELECT "roles"."id" AS t0_r0, "roles"."name" AS t0_r1, "roles"."position" AS t0_r2, "roles"."builtin" AS t0_r3, "roles"."type" AS t0_r4, "roles"."created_at" AS t0_r5, "roles"."updated_at" AS t0_r6, "role_permissions"."id" AS t1_r0, "role_permissions"."permission" AS t1_r1, "role_permissions"."role_id" AS t1_r2, "role_permissions"."created_at" AS t1_r3, "role_permissions"."updated_at" AS t1_r4 FROM "roles" LEFT OUTER JOIN "role_permissions" ON "role_permissions"."role_id" = "roles"."id" WHERE "roles"."id" IN (SELECT "roles"."id" FROM "users" LEFT OUTER JOIN "members" ON "users"."id" = "members"."user_id" AND "members"."project_id" = 5 LEFT OUTER JOIN "member_roles" ON "members"."id" = "member_roles"."member_id" LEFT OUTER JOIN "roles" ON "roles"."id" = "member_roles"."role_id" WHERE "users"."id" = 11)

D, [2022-08-11T10:58:34.712280 #69] DEBUG -- : GitlabMergeRequest Load (0.3ms) SELECT "gitlab_merge_requests".* FROM "gitlab_merge_requests" WHERE ("gitlab_merge_requests"."gitlab_id" = $1 OR "gitlab_merge_requests"."gitlab_html_url" = $2) LIMIT $3 [["gitlab_id", 7], ["gitlab_html_url", "https://xxx/zzz/MServer/-/merge_requests/7"], ["LIMIT", 1]]```

**Comment by btey** [comment]
Hi @NTXPabu 

Could you indicate the installation method used and the steps you followed?

Thanks,
Ben

**Comment by NTXPabu** [comment]
Hi @btey

I created a Gemfile.plugins file with the following content:
```
group :opf_plugins do
  gem "openproject-gitlab_integration", git: "https://github.com/btey/openproject-gitlab-integration.git", branch: "master"
end
```

After that I created a Dockerfile that copys that Gemfile into the image and reruns the bundle install command:
```
FROM openproject/community:12

# If installing a local plugin (using `path:` in the `Gemfile.plugins` above),
# you will have to copy the plugin code into the container here and use the
# path inside of the container. Say for `/app/vendor/plugins/openproject-slack`:
# COPY /path/to/my/local/openproject-slack /app/vendor/plugins/openproject-slack

COPY Gemfile.plugins /app/

# If the plugin uses any external NPM dependencies you have to install them here.
# RUN npm add npm <package-name>*

RUN bundle config unset deployment && bundle install && bundle config set deployment 'true'
RUN ./docker/prod/setup/postinstall.sh
```

After that I created the User for OpenProject and generated the API Key which were used for the Gitlab Webhook.

**Comment by btey** [comment]
Hi @NTXPabu 

After the release of the v12.2.1, the "Fix_compatibilty_with_OpenProject_12.2.0" branch worked without errors building a docker image with the plugin. I'll be merging the fix into the main branch shortly. I add some screenshots.

![Screen Shot 2022-08-22 at 15 34 47](https://user-images.githubusercontent.com/14983519/186009365-5a83a7ad-6236-4246-8af0-588203caba0e.png)

![Screen Shot 2022-08-22 at 15 35 58](https://user-images.githubusercontent.com/14983519/186009383-9dbd5b6c-7968-48a9-a585-07994430c6ba.png)

![Screen Shot 2022-08-22 at 15 36 27](https://user-images.githubusercontent.com/14983519/186009399-daf7d6c9-13d8-4f0c-b3b4-8061c6be0b70.png)

![Screen Shot 2022-08-22 at 15 36 52](https://user-images.githubusercontent.com/14983519/186009416-f374bdf8-09fd-4d84-841b-f271fd748f74.png)

Dockerfile content
```
FROM openproject/community:12

# If installing a local plugin (using `path:` in the `Gemfile.plugins` above),
# you will have to copy the plugin code into the container here and use the
# path inside of the container. Say for `/app/vendor/plugins/openproject-slack`:
# COPY /path/to/my/local/openproject-slack /app/vendor/plugins/openproject-slack

COPY Gemfile.plugins /app/

# If the plugin uses any external NPM dependencies you have to install them here.
# RUN npm add npm <package-name>*

RUN bundle config unset deployment && bundle install && bundle config set deployment 'true'
RUN ./docker/prod/setup/postinstall.sh
```

Gemfile.plugin
```
group :opf_plugins do
  gem "openproject-gitlab_integration", git: "https://github.com/btey/openproject-gitlab-integration.git", branch: "Fix_compatibilty_with_OpenProject_12.2.0"
end
```

When version 2.0.6 is ready try it when you get a chance with v12.2.1 and if you still have problems let me know. Remember to follow the instructions to disable HTTPS in case you don't use it (https://www.openproject.org/docs/installation-and-operations/installation/docker/#all-in-one-container).

Thanks,
Ben

**Comment by btey** [comment]
OpenProject GitLab Integration v2.0.6 release available.

**Comment by NTXPabu** [comment]
Hi @btey 

Im afraid but it is still not working with OpenProject 12.2.1 and your newest Patch. The Merge request still dont show up.
I built a docker image as described with the gitlab Plugin but that also didnt resolve the problem.

When i test the Merge Request in Gitlab i get the following error in OP:

```
D, [2022-08-24T10:58:20.648261 #66] DEBUG -- : Received gitlab webhook merge_request_hook
E, [2022-08-24T10:58:20.649046 #66] ERROR -- : Failed to handle merge_request_hook from Gitlab: key not found: "action" key not found: "action"
E, [2022-08-24T10:58:20.650359 #66] ERROR -- : user=11 key not found: "action": key not found: "action"
D, [2022-08-24T10:58:20.650421 #66] DEBUG -- : [KeyError] key not found: "action": openproject-gitlab-integration (b26bec1c68d2) lib/open_project/gitlab_integration/notification_handler/helper.rb:132:in `method_missing'; openproject-gitlab-integration (b26bec1c68d2) lib/open_project/gitlab_integration/notification_handler/merge_request_hook.rb:48:in `process'; openproject-gitlab-integration (b26bec1c68d2) lib/open_project/gitlab_integration/notification_handlers.rb:44:in `block in merge_request_hook'; openproject-gitlab-integration (b26bec1c68d2) lib/open_project/gitlab_integration/notification_handlers.rb:75:in `with_logging'; openproject-gitlab-integration (b26bec1c68d2) lib/open_project/gitlab_integration/notification_handlers.rb:43:in `merge_request_hook'; lib_static/open_project/notifications.rb:57:in `block in subscribe'; lib_static/open_project/notifications.rb:81:in `send'; openproject-gitlab-integration (b26bec1c68d2) lib/open_project/gitlab_integration/hook_handler.rb:60:in `process'; openproject-gitlab-integration (b26bec1c68d2) lib/open_project/gitlab_integration/engine.rb:55:in `block (2 levels) in <class:Engine>'; modules/webhooks/lib/open_project/webhooks/hook.rb:44:in `handle'; modules/webhooks/app/controllers/webhooks/incoming/hooks_controller.rb:56:in `handle_hook'
```

**Comment by btey** [comment]
Hi @NTXPabu 

I have seen this error before, in the issue #4. The Gitlab installation should not be fine. The "object_attributes.action" key is basic to processing the request, and is described in the Gitlab documentation (https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#merge-request-events).

I would recommend reinstall Gitlab, and/or check if something may be affecting the network so that this information is lost when it reaches OpenProject.

Make sure after activating only the necessary webhooks.

![Screen Shot 2022-08-24 at 08 55 00](https://user-images.githubusercontent.com/14983519/186423717-085566ed-8717-4352-ae77-43317f2cf1bd.png)

In this section of the plugin code you can see where this key is verified: https://github.com/btey/openproject-gitlab-integration/blob/master/lib/open_project/gitlab_integration/notification_handler/merge_request_hook.rb#L48

Thanks,
Ben

**Comment by NTXPabu** [comment]
Hi @btey

Ok we resolved it :). The problem was that the git User in OpenProject needs atleast Member rights to the specific Project so he can comment on the WorkPackage. We completely forgot this step.
And for Issues the User needs Project Admin rights.

But thank you anyways :)

Have a nice day!
