### ISSUE TITLE
Unable to install plugin, Docker installation, OpenProject v12.5.1

### ISSUE THREAD

**Issue by DerpgonCz** [btey/openproject-gitlab-integration#33]
Hello, when trying to install the plugin, the Docker image build crashes during `npm run build` during POSTINSTALL step.

OpenProject: v12.5.1
Plugin: `master` branch
Installation type: Docker

Log:
```
npm run build
W, [2023-07-10T13:21:50.420133 #629]  WARN -- : 127.0.0.1:11211 failed (count: 0) Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 11211
W, [2023-07-10T13:21:50.527178 #629]  WARN -- : 127.0.0.1:11211 failed (count: 1) Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 11211
W, [2023-07-10T13:21:50.527282 #629]  WARN -- : 127.0.0.1:11211 is down
I, [2023-07-10T13:21:52.210698 #629]  INFO -- : Using schema cache file /app/db/schema_cache.yml
Linking frontend plugins
Cleaning linked target directory /app/frontend/src/app/features/plugins/linked
Linking frontend of OpenProject plugin budgets to /app/frontend/src/app/features/plugins/linked/budgets.
Linking frontend of OpenProject plugin costs to /app/frontend/src/app/features/plugins/linked/costs.
Linking frontend of OpenProject plugin openproject-avatars to /app/frontend/src/app/features/plugins/linked/openproject-avatars.
Linking frontend of OpenProject plugin openproject-documents to /app/frontend/src/app/features/plugins/linked/openproject-documents.
Linking frontend of OpenProject plugin openproject-github_integration to /app/frontend/src/app/features/plugins/linked/openproject-github_integration.
Linking frontend of OpenProject plugin openproject-gitlab_integration to /app/frontend/src/app/features/plugins/linked/openproject-gitlab_integration.
Regenerating frontend plugin registry /app/frontend/src/app/features/plugins/linked-plugins.module.ts.
Regenerating frontend plugin sass /app/frontend/src/app/features/plugins/linked-plugins.styles.sass.
Building angular frontend

> openproject-frontend@0.1.0 build
> node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --configuration production --named-chunks --source-map

Option "deployUrl" is deprecated: Use "baseHref" option, "APP_BASE_HREF" DI token or a combination of both instead. For more information, see https://angular.io/guide/deployment#the-deploy-url.
    Components styles sourcemaps are not generated when styles optimization is enabled.
- Generating browser application bundles (phase: setup)...
    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
Processing legacy "View Engine" libraries:
- @uirouter/core [module/esm5] (https://github.com/ui-router/core.git)
- @datorama/akita [es2015/esm2015] (https://github.com/datorama/akita)
- @ng-select/ng-select [es2015/esm2015] (ng-select/ng-select)
- @ng-select/ng-option-highlight [es2015/esm2015] (ng-select/ng-select)
- ng2-dragula [es2015/esm2015] (git+https://github.com/valor-software/ng2-dragula.git)
- ng-dynamic-component [es2015/esm2015] (https://github.com/gund/ng-dynamic-component.git)
- @ngneat/content-loader [es2015/esm2015] (https://github.com/ngneat/content-loader)
- @ngx-formly/core [es2015/esm2015] (git+https://github.com/ngx-formly/ngx-formly.git)
- @kolkov/ngx-gallery [es2015/esm2015] (https://github.com/kolkov/ngx-gallery)
- ng2-charts [es2015/esm2015] (git+https://github.com/valor-software/ng2-charts.git)
- cdk-drag-scroll [es2015/esm2015] (git+https://github.com/volser/cdk-drag-scroll.git)
Encourage the library authors to publish an Ivy distribution.
Killed
rake aborted!
Failed to compile angular frontend: 137
/app/lib/tasks/assets.rake:68:in `block (4 levels) in <top (required)>'
/app/lib/tasks/assets.rake:67:in `block (3 levels) in <top (required)>'
/app/lib/tasks/assets.rake:66:in `chdir'
/app/lib/tasks/assets.rake:66:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:492:in `exec'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => assets:precompile => assets:compile_environment => assets:prepare_op => assets:angular
(See full trace by running task with --trace)
The command '/bin/sh -c ./docker/prod/setup/postinstall.sh' returned a non-zero code: 1
```

Dockerfile
```
FROM openproject/community:12.5.1

COPY Gemfile.plugins /app/

RUN bundle config unset deployment && bundle install && bundle config set deployment 'true'
RUN ./docker/prod/setup/postinstall.sh
```

Gemfile.plugins
```
group :opf_plugins do
  gem "openproject-gitlab_integration", git: "https://github.com/btey/openproject-gitlab-integration.git", branch: "master"
end
```

**Comment by DerpgonCz** [comment]
This was caused by an outdated Docker / Docker-Compose / Docker Compose versions.
Updated to Docker 24.0.4, Docker Compose 2.19.1, all works now.

Closing the issue
