### ISSUE TITLE
Merge Request model not created in DB if the MR does not have a description

### ISSUE THREAD

**Issue by DerpgonCz** [btey/openproject-gitlab-integration#36]
When creating a Merge Request in GitLab, the webhook fails with a 500 error code if the MR does not have a description.

Proposed fix is supplying a default value (for example an empty string), because from what I understand it has to not be `null`.

This could be fixed alongside with #31 - by providing either a static placeholder, or a gravatar URL.

Log:
```
compose-web-1  | E, [2023-07-29T22:38:16.552397 #88] ERROR -- : user=8 Validation failed: Body can't be blank.: Validation failed: Body can't be blank.
compose-web-1  | D, [2023-07-29T22:38:16.552525 #88] DEBUG -- : [ActiveRecord::RecordInvalid] Validation failed: Body can't be blank.: openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/services/upsert_merge_request.rb:40:in `block in call'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/services/upsert_merge_request.rb:39:in `call'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/notification_handler/merge_request_hook.rb:105:in `upsert_merge_request'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/notification_handler/merge_request_hook.rb:63:in `process'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/notification_handlers.rb:44:in `block in merge_request_hook'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/notification_handlers.rb:75:in `with_logging'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/notification_handlers.rb:43:in `merge_request_hook'; lib_static/open_project/notifications.rb:57:in `block in subscribe'; lib_static/open_project/notifications.rb:81:in `send'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/hook_handler.rb:60:in `process'; openproject-gitlab-integration (278f0c3b3c19) lib/open_project/gitlab_integration/engine.rb:55:in `block (2 levels) in <class:Engine>'; modules/webhooks/lib/open_project/webhooks/hook.rb:44:in `handle'; modules/webhooks/app/controllers/webhooks/incoming/hooks_controller.rb:56:in `handle_hook'
compose-web-1  | D, [2023-07-29T22:38:16.560070 #88] DEBUG -- :   Rendering layout layouts/no_menu.html.e
```

Merge Request payload:
```
{
  "object_kind": "merge_request",
  "event_type": "merge_request",
  "user": {
    "id": 37,
    "name": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "username": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "avatar_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "email": "[REDACTED]"
  },
  "project": {
    "id": 78,
    "name": "openproject-integration-test",
    "description": "",
    "web_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "avatar_url": null,
    "git_ssh_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "git_http_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "namespace": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "visibility_level": 10,
    "path_with_namespace": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "default_branch": "master",
    "ci_config_path": "",
    "homepage": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "ssh_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "http_url": "[REDACTED_FOR_ISSUE_PURPOSES]"
  },
  "object_attributes": {
    "assignee_id": null,
    "author_id": 37,
    "created_at": "2023-07-29 22:07:14 UTC",
    "description": "",
    "head_pipeline_id": null,
    "id": 421,
    "iid": 6,
    "last_edited_at": null,
    "last_edited_by_id": null,
    "merge_commit_sha": null,
    "merge_error": null,
    "merge_params": {
      "force_remove_source_branch": "1"
    },
    "merge_status": "preparing",
    "merge_user_id": null,
    "merge_when_pipeline_succeeds": false,
    "milestone_id": null,
    "source_branch": "task/6",
    "source_project_id": 78,
    "state_id": 1,
    "target_branch": "master",
    "target_project_id": 78,
    "time_estimate": 0,
    "title": "[#6] Create sponsorship brochure and hand-outs OP#6",
    "updated_at": "2023-07-29 22:07:14 UTC",
    "updated_by_id": null,
    "url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "source": {
      "id": 78,
      "name": "openproject-integration-test",
      "description": "",
      "web_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "avatar_url": null,
      "git_ssh_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "git_http_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "namespace": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "visibility_level": 10,
      "path_with_namespace": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "default_branch": "master",
      "ci_config_path": "",
      "homepage": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "ssh_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "http_url": "[REDACTED_FOR_ISSUE_PURPOSES]"
    },
    "target": {
      "id": 78,
      "name": "openproject-integration-test",
      "description": "",
      "web_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "avatar_url": null,
      "git_ssh_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "git_http_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "namespace": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "visibility_level": 10,
      "path_with_namespace": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "default_branch": "master",
      "ci_config_path": "",
      "homepage": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "ssh_url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "http_url": "[REDACTED_FOR_ISSUE_PURPOSES]"
    },
    "last_commit": {
      "id": "b2cbd17f5e3617dba145049bb25e0889c602fa8e",
      "message": "Update README.md",
      "title": "Update README.md",
      "timestamp": "2023-07-29T19:41:28+00:00",
      "url": "[REDACTED_FOR_ISSUE_PURPOSES]",
      "author": {
        "name": "[REDACTED_FOR_ISSUE_PURPOSES]",
        "email": "[REDACTED]"
      }
    },
    "work_in_progress": false,
    "total_time_spent": 0,
    "time_change": 0,
    "human_total_time_spent": null,
    "human_time_change": null,
    "human_time_estimate": null,
    "assignee_ids": [

    ],
    "reviewer_ids": [

    ],
    "labels": [

    ],
    "state": "opened",
    "blocking_discussions_resolved": true,
    "first_contribution": true,
    "detailed_merge_status": "mergeable",
    "action": "open"
  },
  "labels": [

  ],
  "changes": {
  },
  "repository": {
    "name": "openproject-integration-test",
    "url": "[REDACTED_FOR_ISSUE_PURPOSES]",
    "description": "",
    "homepage": "[REDACTED_FOR_ISSUE_PURPOSES]"
  }
}
```

**Comment by btey** [comment]
Hello @DerpgonCz,

In general, if you follow best practices when using GitLab you should never have an MR without a description. Surely you are creating MR directly without description.

Point 1 of the best practices describes the use of branches (see point 1 -- https://about.gitlab.com/topics/version-control/what-are-gitlab-flow-best-practices). To use branches, you simply start by creating an Issue (with OP# or PP#) in GitLab and from there its corresponding Merge Request. This will create a branch for your work, and you will see that the MR description will never be empty.

Regards,
Ben

**Comment by foxweb** [comment]
@DerpgonCz fixed.

**Comment by DerpgonCz** [comment]
@foxweb Many thanks

@btey When working on an internal project, the MR does not usually need a description. The description is already in a ticket associated with it. We do not use GitLab flow, we have to adhere to other special rules to make sure everything works with out processes. But I understand. Thanks
